dist: xenial
language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  # - 'pypy2.7-6.0'
  - 'pypy3.5-6.0'

env:
  global:
    - COVERAGE_PROCESS_START=$PWD/tox.ini
  matrix:
    - DEPS="pytest~=2.9.0"
    - DEPS="pytest~=3.0.0"
    #- DEPS="pytest~=3.1.0"

stages:
  - name: test
    if: tag IS NOT present
  - name: deploy
    if: repo = pytest-dev/py AND tag IS present

matrix:
  include:
    - python: '2.7'
      # using a different option due to pytest-addopts pytester issues
      env: PYTEST_XADDOPTS="-n auto --runslowtests" DEPS="pytest~=3.0.0 pytest-xdist<1.25 pytest-forked<0.3"

    - stage: deploy
      python: '3.6'
      env:
      install: pip install -U setuptools setuptools_scm
      script: skip
      deploy:
        provider: pypi
        user: nicoddemus
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        password:
          secure: VNYW/sZoD+9DzKCe6vANNXXJR7jP7rwySafQ33N1jAnCrdylQjEN/p6tSfUe8jDi3wDpLPL9h8pwfxuUT7CRxglHov3Qe7zSeywixvHan5aFahQiQ8+gucYIM7wITHH3oQs7jN35pnhdnF+QlW2+eDCL6qOLU5XwuRhsDKXjQ/hUWR5hlX5EniD1gzyKEf6j1YCpST87tKpeLwVEYEmsucdkUZuXhxDtyaWQHWiPsLWwh/slQtUJEHeLF26r8UxFy0RiGne9jR+CzRfH5ktcA9/pArvp4VuwOii+1TDxVSYP7+I8Z+eUKN9JBg12QLaHwoIN/8J+MvHCkuf+OGSLM3sEyNRJGDev372xg3K7ylIkeeK4WXirKEp2ojgN8tniloDjnwdu/gPWBnrXuooA60tNoByHFa8KbMZAr2B2sQeMxD4VZGr1N8l0rX4gRTrwvdk3i3ulLKVSwkXaGn+GrfZTTboa7dEnpuma8tv1niNCSpStYIy7atS8129+5ijV3OC8DzOMh/rVbO9WsDb/RPG3yjFiDvEJPIPeE0l/m5u42QBqtdZSS2ia7UWTJBiEY09uFMTRmH5hhE/1aiYBbvAztf5CReUbeKdSQz3L8TTSZqewtFZmXTkX97/xQnrEpsnGezIM2DNuMEuQG3MxGkNCxwbQKpx/bkHdrD75yMk=
        on:
          tags: true
          repo: pytest-dev/py

  exclude:
    - python: '3.7'
      env: DEPS="pytest~=2.9.0"

  allow_failures:
  - python: 'pypy2.7-6.0'
  - python: 'pypy3.5-6.0'

install:
  - pip install -U coverage coverage-enable-subprocess pip setuptools setuptools_scm
  - pip install $DEPS
  - pip install -U . --force-reinstall

script:
  - coverage run -m pytest --lsof $PYTEST_XADDOPTS

after_success:
  - coverage combine
  - coverage report -m
  - coverage xml
  - bash <(curl -s https://codecov.io/bash) -Z -X gcov -X coveragepy -X search -X xcode -X gcovout -X fix -f coverage.xml -e TRAVIS_PYTHON_VERSION
