environment:
  matrix:
  # note: please use "tox --listenvs" to populate the build matrix below
  - TOXENV: "py27-pytest29"
  - TOXENV: "py27-pytest30"
  - TOXENV: "py27-pytest31"
  - TOXENV: "py35-pytest29"
  - TOXENV: "py35-pytest30"
  - TOXENV: "py35-pytest31"
  - TOXENV: "py36-pytest29"
  - TOXENV: "py36-pytest30"
  - TOXENV: "py36-pytest31"
  - TOXENV: "py37-pytest30"
  - TOXENV: "py37-pytest31"

install:
  - echo Installed Pythons
  - dir c:\Python*

  - C:\Python37\python -m pip install --upgrade --pre tox

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - C:\Python37\python -m tox

# We don't deploy anything on tags with AppVeyor, we use Travis instead, so we
# might as well save resources
skip_tags: true
